/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexiq_rp1210test_Rp1210Lib */

#ifndef _Included_com_nexiq_rp1210test_Rp1210Lib
#define _Included_com_nexiq_rp1210test_Rp1210Lib
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_nexiq_rp1210test_Rp1210Lib
 * Method:    Rp1210Test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nexiq_rp1210test_Rp1210Lib_Rp1210Test
  (JNIEnv *, jobject, jstring str_path);


#ifdef __cplusplus
}
#endif
#endif
